"""Increase length of ScanResult issue column

Revision ID: 6c8a078c0d28
Revises: 5b1f731d057c
Create Date: 2025-08-12 17:25:09.542541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8a078c0d28'
down_revision = '5b1f731d057c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_result', schema=None) as batch_op:
        batch_op.alter_column('issue',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_result', schema=None) as batch_op:
        batch_op.alter_column('issue',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
