"""Initial migration

Revision ID: 7aeda814004e
Revises: 
Create Date: 2025-08-12 11:58:02.487792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aeda814004e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('otp_secret', sa.String(length=32), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('inactivity_timeout', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('backup_email', sa.String(length=120), nullable=True),
    sa.Column('backup_email_verified', sa.Boolean(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('report_schedule', sa.String(length=20), nullable=False),
    sa.Column('report_day', sa.String(length=10), nullable=True),
    sa.Column('report_credential_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backup_email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('details', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('aws_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=64), nullable=False),
    sa.Column('access_key_id', sa.String(length=128), nullable=False),
    sa.Column('encrypted_secret_access_key', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('issue', sa.String(length=256), nullable=True),
    sa.Column('remediation', sa.String(length=512), nullable=True),
    sa.Column('doc_url', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_result_service'), ['service'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_result_timestamp'), ['timestamp'], unique=False)

    op.create_table('suppressed_finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('finding_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('suppress_until', sa.DateTime(), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('issue', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppressed_finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppressed_finding_finding_hash'), ['finding_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppressed_finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppressed_finding_finding_hash'))

    op.drop_table('suppressed_finding')
    with op.batch_alter_table('scan_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_result_timestamp'))
        batch_op.drop_index(batch_op.f('ix_scan_result_service'))

    op.drop_table('scan_result')
    op.drop_table('aws_credential')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
